# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: project-web 
  labels:
    app: web
spec:
  containers:
  - name: project-web
    image: timmyrectommy/web-img:v2