apiVersion: v1
kind: Service
metadata:
  name: project-web
    # namespace: web
spec:
  selector:
     app: web
  ports:
     - name: project-web
       port: 80
       nodePort: 30201
  type: NodePort
